name: macos-arm-build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - run: cd gui
    - run: yarn install
    - run: NODE_OPTIONS="--max-old-space-size=4096" yarn tauri build
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./src-tauri/target/release/bundle/dmg/ZTMesh_0.1.0_aarch64.dmg
