name: windows-build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: build app
      run: |
        cd gui
        yarn install
        NODE_OPTIONS="--max-old-space-size=4096" yarn tauri build
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./gui/src-tauri/target/release/bundle/dmg/ZTMesh_0.1.0_aarch64.dmg
